// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMWNI-wIF1WiS3YOY4x0RfkW1QCNpyX8',
    appId: '1:927958626697:web:c08c15629b502ffc553158',
    messagingSenderId: '927958626697',
    projectId: 'ppb-test-crud-1',
    authDomain: 'ppb-test-crud-1.firebaseapp.com',
    storageBucket: 'ppb-test-crud-1.firebasestorage.app',
    measurementId: 'G-89WBES5GEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsettEw4JfjugqiIF_Ex0JIcCZQWKvZk',
    appId: '1:927958626697:android:5e2bedbda8686a2b553158',
    messagingSenderId: '927958626697',
    projectId: 'ppb-test-crud-1',
    storageBucket: 'ppb-test-crud-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsYMAVetZcB3Uexc2p_1ujLZMOSNsF4Y',
    appId: '1:927958626697:ios:0dedd9355fe095ef553158',
    messagingSenderId: '927958626697',
    projectId: 'ppb-test-crud-1',
    storageBucket: 'ppb-test-crud-1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfsYMAVetZcB3Uexc2p_1ujLZMOSNsF4Y',
    appId: '1:927958626697:ios:0dedd9355fe095ef553158',
    messagingSenderId: '927958626697',
    projectId: 'ppb-test-crud-1',
    storageBucket: 'ppb-test-crud-1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMWNI-wIF1WiS3YOY4x0RfkW1QCNpyX8',
    appId: '1:927958626697:web:36952279fcc375fc553158',
    messagingSenderId: '927958626697',
    projectId: 'ppb-test-crud-1',
    authDomain: 'ppb-test-crud-1.firebaseapp.com',
    storageBucket: 'ppb-test-crud-1.firebasestorage.app',
    measurementId: 'G-R6E1S4XLY7',
  );
}
